// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/compare" | "/results" | "/tools"
type AppRouteHandlerRoutes = "/api/action-plan" | "/api/air-quality" | "/api/analyze/bill" | "/api/analyze/street" | "/api/chat" | "/api/conditions-brief" | "/api/cooling" | "/api/forecast" | "/api/green-times" | "/api/heat-profile" | "/api/historical" | "/api/local-resources" | "/api/reverse-geocode" | "/api/satellite" | "/api/vulnerability"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/action-plan": {}
  "/api/air-quality": {}
  "/api/analyze/bill": {}
  "/api/analyze/street": {}
  "/api/chat": {}
  "/api/conditions-brief": {}
  "/api/cooling": {}
  "/api/forecast": {}
  "/api/green-times": {}
  "/api/heat-profile": {}
  "/api/historical": {}
  "/api/local-resources": {}
  "/api/reverse-geocode": {}
  "/api/satellite": {}
  "/api/vulnerability": {}
  "/compare": {}
  "/results": {}
  "/tools": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
