// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/compare/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compare">> = Specific
  const handler = {} as typeof import("../../../app/compare/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/results/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/results">> = Specific
  const handler = {} as typeof import("../../../app/results/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/tools/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tools">> = Specific
  const handler = {} as typeof import("../../../app/tools/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/action-plan/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/action-plan">> = Specific
  const handler = {} as typeof import("../../../app/api/action-plan/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/air-quality/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/air-quality">> = Specific
  const handler = {} as typeof import("../../../app/api/air-quality/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/analyze/bill/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analyze/bill">> = Specific
  const handler = {} as typeof import("../../../app/api/analyze/bill/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/analyze/street/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/analyze/street">> = Specific
  const handler = {} as typeof import("../../../app/api/analyze/street/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat">> = Specific
  const handler = {} as typeof import("../../../app/api/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/conditions-brief/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/conditions-brief">> = Specific
  const handler = {} as typeof import("../../../app/api/conditions-brief/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/cooling/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cooling">> = Specific
  const handler = {} as typeof import("../../../app/api/cooling/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/forecast/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/forecast">> = Specific
  const handler = {} as typeof import("../../../app/api/forecast/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/green-times/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/green-times">> = Specific
  const handler = {} as typeof import("../../../app/api/green-times/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/heat-profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/heat-profile">> = Specific
  const handler = {} as typeof import("../../../app/api/heat-profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/historical/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/historical">> = Specific
  const handler = {} as typeof import("../../../app/api/historical/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/local-resources/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/local-resources">> = Specific
  const handler = {} as typeof import("../../../app/api/local-resources/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/reverse-geocode/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reverse-geocode">> = Specific
  const handler = {} as typeof import("../../../app/api/reverse-geocode/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/satellite/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/satellite">> = Specific
  const handler = {} as typeof import("../../../app/api/satellite/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/vulnerability/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/vulnerability">> = Specific
  const handler = {} as typeof import("../../../app/api/vulnerability/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
